### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by RiweiPan** [WiscADSL/uFS#1]
Dear developers, 

Thank you very much for providing such an excellent job, I would like to learn the design and code of uFS, but I encounter some compilation problems:

My building environments:
Ubutun 20.04
gcc-9 & g++-9
cmake 3.16.3

The steps are as follow:

> git clone https://github.com/WiscADSL/uFS.git
git submodule update --init
cd cfs
mkdir build && cd build
cmake ..

the output after running `cmake` are:
> -- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.51.0") found components: context filesystem program_options regex system thread 
-- Found folly: /usr/local
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Using bundled config4cpp
-- Using bundled tbb
MAIN_NAME: fsMain
release mode
CFS_BUILD:
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hubery/mywork/U-SSD/test/uFS/cfs/build

Then, after execuating  `make -j8`, I get some error message:
> /usr/bin/ld: cannot find -lspdk
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cfspg.dir/build.make:264: libcfspg.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:782: CMakeFiles/cfspg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object lib/abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/sysinfo.cc.o
[ 17%] Linking CXX static library libabsl_throw_delegate.a
[ 17%] Built target absl_throw_delegate
[ 18%] Building CXX object lib/abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/thread_identity.cc.o
[ 18%] Building CXX object lib/abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/unscaledcycleclock.cc.o
[ 18%] Linking CXX static library libabsl_base.a
[ 18%] Built target absl_base
[ 18%] Linking CXX executable fsTest_FsImpl_MemBufLayout
[ 18%] Built target fsTest_FsImpl_MemBufLayout
[ 18%] Linking CXX static library ../../../lib/libgtest.a
[ 18%] Built target gtest
[ 18%] Linking CXX executable fsProcDumpMetadata
/usr/bin/ld: cannot find -lspdk
collect2: error: ld returned 1 exit status
make[2]: *** [test/fsproc/CMakeFiles/fsProcDumpMetadata.dir/build.make:123: test/fsproc/fsProcDumpMetadata] Error 1
make[1]: *** [CMakeFiles/Makefile2:3405: test/fsproc/CMakeFiles/fsProcDumpMetadata.dir/all] Error 2
[ 18%] Linking CXX executable fsProcOfflineCheckpointer
/usr/bin/ld: cannot find -lspdk
collect2: error: ld returned 1 exit status
make[2]: *** [test/fsproc/CMakeFiles/fsProcOfflineCheckpointer.dir/build.make:138: test/fsproc/fsProcOfflineCheckpointer] Error 1
make[1]: *** [CMakeFiles/Makefile2:3432: test/fsproc/CMakeFiles/fsProcOfflineCheckpointer.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Could you give me some suggestion to address the problem? Thank you!

**Comment by jingliu9** [comment]
Hi Riwei,

It looks you need to build SPDK (`/usr/bin/ld: cannot find -lspdk`).

Please refer to this section in the artifact evaluation [document](https://github.com/WiscADSL/uFS/tree/main/cfs_bench/exprs/artifact_eval#initialization) and this part of code in our script [install code in script](https://github.com/WiscADSL/uFS/blob/16e915baa6bcc6813bf4a999abbd853822028a29/cfs_bench/exprs/artifact_eval/artifact_eval.sh#L222)

Thanks!

**Comment by RiweiPan** [comment]
Hi jingliu, thank you very much for your kind reply!

I've tried again with the help of artifact_eval.sh. It worked very well on my machine. But when I tried to run uFS by:
> ./artifact_eval.sh cmpl microbench ufsnj

There are still some compile errors about spdlog and the relevant information are:

> hubery@hserver:artifact_eval$ ./artifact_eval.sh cmpl microbench ufsnj > output.txt
Already on 'main'
MAIN_NAME: fsMain
release mode
CFS_BUILD:
MAIN_NAME: fsMain
release mode
CFS_BUILD:
In file included from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/spdlog.h:12,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/basic_file_sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_WorkerComm.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:27,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h: In constructor ‘spdlog::spdlog_ex::spdlog_ex(const string&, int)’:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h:186:54: error: cannot convert ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const char*’
  186 |         fmt::format_system_error(outbuf, last_errno, msg);
      |                                                      ^~~
      |                                                      |
      |                                                      const string {aka const std::__cxx11::basic_string<char>}
In file included from /usr/local/include/folly/Range.h:45,
                 from /usr/local/include/folly/container/HeterogeneousAccess.h:22,
                 from /usr/local/include/folly/concurrency/detail/ConcurrentHashMap-detail.h:23,
                 from /usr/local/include/folly/concurrency/ConcurrentHashMap.h:23,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:4,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/usr/local/include/fmt/format.h:2471:46: note:   initializing argument 3 of ‘void fmt::v8::format_system_error(fmt::v8::detail::buffer<char>&, int, const char*)’
 2471 |                                  const char* message) FMT_NOEXCEPT;
      |                                  ~~~~~~~~~~~~^~~~~~~
In file included from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/pattern_formatter.h:8,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/logger.h:23,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/registry.h:15,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/spdlog.h:13,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/basic_file_sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_WorkerComm.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:27,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/fmt_helper.h: In function ‘unsigned int spdlog::details::fmt_helper::count_digits(T)’:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/fmt_helper.h:50:39: error: ‘fmt::internal’ has not been declared
   50 |     return static_cast<unsigned>(fmt::internal::count_digits(static_cast<count_type>(n)));
      |                                       ^~~~~~~~
In file included from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/spdlog.h:12,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/basic_file_sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_WorkerComm.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:27,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h: In constructor ‘spdlog::spdlog_ex::spdlog_ex(const string&, int)’:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h:186:54: error: cannot convert ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const char*’
  186 |         fmt::format_system_error(outbuf, last_errno, msg);
      |                                                      ^~~
      |                                                      |
      |                                                      const string {aka const std::__cxx11::basic_string<char>}
In file included from /usr/local/include/folly/Range.h:45,
                 from /usr/local/include/folly/container/HeterogeneousAccess.h:22,
                 from /usr/local/include/folly/concurrency/detail/ConcurrentHashMap-detail.h:23,
                 from /usr/local/include/folly/concurrency/ConcurrentHashMap.h:23,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:4,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/usr/local/include/fmt/format.h:2471:46: note:   initializing argument 3 of ‘void fmt::v8::format_system_error(fmt::v8::detail::buffer<char>&, int, const char*)’
 2471 |                                  const char* message) FMT_NOEXCEPT;
      |                                  ~~~~~~~~~~~~^~~~~~~
In file included from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/pattern_formatter.h:8,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/logger.h:23,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/registry.h:15,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/spdlog.h:13,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/basic_file_sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_WorkerComm.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:27,
                 from /home/hubery/workspace/uFS/cfs/src/BlkDevSpdk.cc:14:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/fmt_helper.h: In function ‘unsigned int spdlog::details::fmt_helper::count_digits(T)’:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/details/fmt_helper.h:50:39: error: ‘fmt::internal’ has not been declared
   50 |     return static_cast<unsigned>(fmt::internal::count_digits(static_cast<count_type>(n)));
      |                                       ^~~~~~~~
In file included from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/spdlog.h:12,
                 from /home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/sinks/basic_file_sink.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_WorkerComm.h:9,
                 from /home/hubery/workspace/uFS/cfs/include/FsProc_Fs.h:27,
                 from /home/hubery/workspace/uFS/cfs/src/FsProc.cc:10:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h: In constructor ‘spdlog::spdlog_ex::spdlog_ex(const string&, int)’:
/home/hubery/workspace/uFS/cfs/lib/spdlog/spdlog/common.h:186:54: error: cannot convert ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const char*’
  186 |         fmt::format_system_error(outbuf, last_errno, msg);
      |                                                      ^~~
      |                                                      |
      |                                                      const string {aka const std::__cxx11::basic_string<ch

Was there anything missing in the previous steps? Thank you again for your kind help!

**Comment by jingliu9** [comment]
Hi,

Could you please check your gcc/g++ version? This looks the problem comes from building `spdlog` (which is one third-party library); as such, it might work better to refer to the building instruction of [its original repo](https://github.com/gabime/spdlog).

According to our experience, it would help to read the whole document of artifact evaluation [README.md](https://github.com/WiscADSL/uFS/blob/main/cfs_bench/exprs/artifact_eval/README.md). It is likely to work smoothly. (We kind of document the version dependency here and there in the document)

Specifically for your question, this might help [StackOverflow answer for the compiler error](https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring).

Thanks

**Comment by RiweiPan** [comment]
OK, thanks for your help!

**Comment by RiweiPan** [comment]
Hi, I have fixed the compilation problem. After I downloaded folly-2020.07.20.00, I tried to compile it and the compiler (g++-10) reported  `template with C linkage ` errors. The error is from the source files about IO_Uring in `experimental/io/` folder. I removed these files and then compiled folly successfully. The compilation of uFS was also successfully after installed this folly.

Thanks again for your help!  You may close the issue.

**Comment by jingliu9** [comment]
Thanks! Glad it works now. :)
